### ISSUE TITLE
Windows app keeps crashing 

### ISSUE THREAD

**Issue by kpaddie** [Polarrco/polarr_windows_support#1]
Windows app keeps crashing on my Microsoft 12.3" Surface Pro 4 256GB.

**Comment by phxchristian** [comment]
BTW, kpaddie needs to mention when the app is crashing...

On my Microsoft Surface Pro 3 w/ 128GB, Polarr Photo Editor Pro force closes when trying to save or export the image I just edited.  Please fix this as this is pitiful.  It's a travesty that you, the developer or developers originally wanted $20.00 for an app with these kinds of problems not being sorted out.  Luckily I bought it for .99 cents as a deal, I can't imagine how those who paid full price would feel knowing the app works up until you want to make a copy of your image that you spent so much time editing.

**Comment by mattpoe** [comment]
I've got the exact same setup and issue as phxchristian, except I paid 9.99.  I did see a notice a week or two ago that a new release was due in May.  I was hopeful this would resolve the problem.  I absolutely love the app.  You've combined highly technical image processing settings with an easy to use interface.  Now let me have my image please.  Or give me Power User access via the browser app.

**Comment by Kenya-West** [comment]
Same here. I have paid for nothing. My specs:

- AMD Radeon R9 390X: Crimson 16.2.5.1 beta drivers
- Windows 10 build .318

**Comment by StefEBear** [comment]
I am also having the same problem on Both Windows 10 Laptop and my Surface 3 Tablet. The software crashes each time I try to save a file.

**Comment by mtoweber** [comment]
This was working for me until very recently and then started virtually overnight. It does not happen for all files. It definitely happens to all files which have been edited before (and saved), but it also happens for some others (and it seems to be persistent for these files). 

I first suspected location - no hit. Then check orientation and dimension - again no definite hit. Metadata (application) - no hit. File type - no hit. 

I originally suspected an initialization error for the Save File dialog - looks unlikely.

The thing is, the app crashes before it ever brings up the the "Saving Photo" print, which likely points to some processing before entering this stage (maybe final rendering). As this was working until recently (and now fails on the same files which previously worked), without an update being installed, but works sometimes, it smells like uninitilialized or overwritten variable, somewhere....

**Comment by mtoweber** [comment]
Polar WILL WORK correctly if the Location Info (DOP) is missing from the original file (check in Polarr with Image Info). This info seems to be written only by the Windows 10 photo editor. 

Easiest way to get rid of it I found so far (you'll loose your Exif info): Load it in any graphics program (not Microsoft) and store it as BMP.

**Comment by bwang29** [comment]
@mtoweber This is very useful info. Can you attach a sample photo to us or send to support@polarr.co for us to debug the DOP?
