### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Emilytc** [Polarrco/polarr_windows_support#10]
I just recently bought this app, but every time I go to import one of my pictures it gives me an error reading "Display driver intel HD graphics driver for windows 8(R) stopped responding and has successfully recovered" I'm really hoping i didn't just waste $20 dollars. if you know what could be wrong please let me know!  

Emily

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.
