### ISSUE TITLE
Aplication: Polarr for Windows 10

### ISSUE THREAD

**Issue by thaissadib** [Polarrco/polarr_windows_support#11]
![polarr 2](https://cloud.githubusercontent.com/assets/19917503/16024415/13d876e6-3198-11e6-9af7-e7ff656c5469.png)
![polarr 3](https://cloud.githubusercontent.com/assets/19917503/16024416/13dd24a2-3198-11e6-91eb-5f104323a2e9.png)
![polarr](https://cloud.githubusercontent.com/assets/19917503/16024417/13e4bcd0-3198-11e6-8da7-15e3e976bfb5.png)

Hello, I wish to know how do I get the devolution of my money by the Polarr application
 for Windows. I would like to purchase the Polarr Web Browser, but I don’t want to pay again for the app, because Polarr for Windows doesn’t open, I buy it and install it in this very moment, how it doesn’t open. As I could see this isn’t only my problem, it recurs a lot among the users of the application for Windows. **What solution can you offer me, devolution of my money for buy the Web Browser version, transfer a permission for me to use the Web Browser version, or fix the problem of the Windows app?**

**Comment by kpaddie** [comment]
Hello,

The Windows Store does not allow for refunds, so the easiest possibility in this case is to allow you access to pro features on the web version. Here is an unlock code for the web version: YREA3-TTHC6-BN8J3-JQZTH-QN2GC

We have recently updated the windows versions (free and paid), and they may now work for you.

Best,

-Polarr team

**Comment by thaissadib** [comment]
Where should I insert this code?

**Comment by kpaddie** [comment]
Try the web version at photoeditor.polarr.co. You can click the "man" profile icon on the upper left-hand corner and "Upgrade to Pro", where you can insert the code.

**Comment by thaissadib** [comment]
When I click in the upload link. I'm routed to the form of payment window.
How should I proceed?

Em 28 de jul de 2016 15:45, "kpaddie" <notifications@github.com> escreveu:

**Comment by kpaddie** [comment]
Hi there,

With a free unlock code, you must download Polarr for Chrome (https://chrome.google.com/webstore/detail/polarr-photo-editor-3/djonnbgfieijldcieafgjcnhmpcfpmgg).

You can enter the code here.

Best,

-Polarr team
