### ISSUE TITLE
The Polarr software is bug 

### ISSUE THREAD

**Issue by ABlumental** [Polarrco/polarr_windows_support#12]
The Polarr software is bug and does not work in my conputador. What procedure should I do to use the software?
My computer is running Windows 10, 64.
You should better test the software before selling.
Await response.

**Comment by kpaddie** [comment]
Hello,

We have recently updated the free and paid versions for Windows 10. You may upgrade, and, if your issue persists, please email support@polarr.co.

Thank you.

Best,

-Polarr team
