### ISSUE TITLE
FR: Missing features for creating time-lapse videos

### ISSUE THREAD

**Issue by mightycoco** [Polarrco/polarr_windows_support#13]
To complete the workflow for time-lapse videos there are two major features missing.

1. Ability to apply a (custom) filter to all open files OR apply specific filter when doing a batch-export
2. Loading RAW images (which is not available for Windows Desktop / Windows App afaik)

This would be my selling two points to buy the pro-version.

**Comment by kpaddie** [comment]
Hi there,

Thank you for your suggestions, and we will consider them for future development.

Note: the newly-released updated for the Windows 10 app allow batch filter and exporting. There is also experimental RAW support available for some file sizes and RAW formats.

Best,

-Polarr team
