### ISSUE TITLE
Couldn't save photo

### ISSUE THREAD

**Issue by suesskind78** [Polarrco/polarr_windows_support#14]
I use the brand new edition of polarr photo editor pro (Version 2.1.34.0) for Windows 10 but i'm not able to safe any of my pictures. Please fix it!

**Comment by kpaddie** [comment]
Hi there,

What device and OS are you using? Can you send one of the photos you were attempting to edit to support@polarr.co? (This will help us diagnose the problem).

**Comment by suesskind78** [comment]
Hi Daniel,

Thanks for your patience!

​The app save issues have been fixed in the new updated version. You may go
try it out.

Best,


-- Borui, Founder and CEO, peer support @ www.polarr.co
If you love our app, please leave us a review : )
Daniel Vogelsberg on August 4, 2016 at 7:45am wrote:

Hi all,

I posted the issue to github.com:

https://github.com/Polarrco/polarr_windows_support/issues/14

I use Polarr on a Surface 3 Pro with Windows 10 Pro, 1607 (Build 14393.10)
and I can reproduce the bug no matther which picture I'm trying to edit.
Anyway, here's the image.

Best,

Daniel



*Von:* kpaddie [mailto:notifications@github.com]
*Gesendet:* Mittwoch, 3. August 2016 20:49
*An:* Polarrco/polarr_windows_support <
polarr_windows_support@noreply.github.com>
*Cc:* suesskind78 <postkarte@live.de>; Author <author@noreply.github.com>
*Betreff:* Re: [Polarrco/polarr_windows_support] Couldn't save photo (#14)



Hi there,

What device and OS are you using? Can you send one of the photos you were
attempting to edit to support@polarr.co? (This will help us diagnose the
problem).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Polarrco/polarr_windows_support/issues/14#issuecomment-237333580>,
or mute the thread
