### ISSUE TITLE
PolarrWinX64Setup folder contains "__MACOSX" system folder

### ISSUE THREAD

**Issue by dollar-sign** [Polarrco/polarr_windows_support#15]
My system
Windows 8.1
64 bit

How to reproduce
1. Go to https://www.polarr.co/
2. Download archive for windows "PolarrWinX64Setup" (in my case it is 64 bit)
3. Unzip it

It seems like it was packed on Mac OS thus it created a system folder.

![bug](https://cloud.githubusercontent.com/assets/16760360/17649158/5223559a-61e2-11e6-8e54-6784ca16bfc1.png)

**Comment by kpaddie** [comment]
Hi there, 

Does the program still work as intended?

**Comment by dollar-sign** [comment]
Yes, sure. Just a little imperfection. Program works fine!
