### ISSUE TITLE
Plz update the windows version

### ISSUE THREAD

**Issue by Morrostar** [Polarrco/polarr_windows_support#16]
The chrome version and mobile version had all the features now, but the windows version (even after upgraded to pro) had none of these features posted on the official website: like fx and blur.

**Comment by kpaddie** [comment]
Hi Morrostar,

Have you updated to the latest version on the Windows Store? If so, can you send a screenshot of your screen to support@polarr.co?

Best,

-Polarr team

**Comment by Morrostar** [comment]
Hi kpaddie,
The windows version I mentioned was meant to be the desktop version, running on Windows7,8.....you know, not all the customers wanna upgrade to win10, therefore the win10-exclusive windows store could not be applied to all....
