### ISSUE TITLE
Windows License

### ISSUE THREAD

**Issue by RiTCHiE007NL** [Polarrco/polarr_windows_support#19]
I bought a license for polarr trough the polarr website and have activated the windows version and i know it can be used on 3 different PC's. Now i would like to know if i delete the app and reinstall it on the same system that has been activated already, would that count as a new activation or does it pick up the old one? Also what if i activate the browser version of Polarr on the same system? Will that count for a new activation? And when i have activated the web version, will it be tied to a account? And can it be used when i log into the web version from a different computer?

Hope i can get some awnsers on these questions.

kind regards,

Richard

**Comment by kpaddie** [comment]
Hi Richard,

Thanks for reaching out. Deleting and reinstalling may require a new use of the unlock code. The browser version of Polarr also counts as a new activation. The web version is also tied to an account login. 

Very best,

-Polarr team

**Comment by RiTCHiE007NL** [comment]
Well i activated the web version trough chrome and when i login on the web version from microsoft edge browser it says its not the full version even tho i used the same account that i already activated in chrome.
