### ISSUE TITLE
Export to an user specified path

### ISSUE THREAD

**Issue by chengchengccc** [Polarrco/polarr_windows_support#2]
Currently polarr only export files to windows picture directory, could you add a menu to export files to an user specified path

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver. It will also allow custom export directory.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.
