### ISSUE TITLE
Problem with editing pictures

### ISSUE THREAD

**Issue by moli111** [Polarrco/polarr_windows_support#20]
While editing a picture in Polarr Pro version on Windows 10, the picture is still moving with the cursor and makes editing almost impossible especially while using tools like Gradient mask or 
Brush mask. I don't have this problem with android version. Let me know how to fix this problem and make using Polarr possible again.

**Comment by SiruiSun** [comment]
I have this problem on Win 10 as well. Hope to solve them as soon as possible.

**Comment by kpaddie** [comment]
Hi there,

This is a bug we are currently working on. We hope to have it resolved soon.

Best,

-Polarr team
