### ISSUE TITLE
Problem in filters after last update

### ISSUE THREAD

**Issue by vitriolv** [Polarrco/polarr_windows_support#21]
Hi
Since the new update to version 2.1.65.0 the vertical left slide to set 
the filters intensity doesn't work anymore. The cursor is blocked, and 
if I try to move it, the picture turn all black. It's completely unusable.
I use Photo Editor Pro|Polarr under Windows 10 Desktop (PC).
Thanks in advance for your support.

Cheers
Renzo

**Comment by kpaddie** [comment]
Hi Renzo,

This issue has been resolved, and will be released with the next update.

Best,

-Polarr team
