### ISSUE TITLE
Polarr setup doesnt work 

### ISSUE THREAD

**Issue by Pitrssoucek** [Polarrco/polarr_windows_support#22]
Hi,

I just downloaded Polarr for windows 7 and the instalation app keeps crashing. It loads up to half of the instalation bar and then crashes. 
![screenshot_1](https://cloud.githubusercontent.com/assets/23419755/20238745/6b525e06-a8f2-11e6-97de-f0ca9afc7a9c.png)
Please help. Thank you.

**Comment by bwang29** [comment]
Hello, we no longer supports Windows 7 and recommend you use our Chrome app at https://www.polarr.co/chrome
