### ISSUE TITLE
Unreadable saved file

### ISSUE THREAD

**Issue by vaschoepfer** [Polarrco/polarr_windows_support#3]
When I try to save, sometimes it works, sometimes it saves an unreadable file that my computer can't open.  It usually does this if I try to save it (it works) then make adjustments and save a new version with a different name.

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.
