### ISSUE TITLE
Polarr won't open

### ISSUE THREAD

**Issue by kasugasan** [Polarrco/polarr_windows_support#4]
I used Polarr and then closed it to do other things. When I want to work on my photos again, it won't open (with a 'not responding' message) and then crashes. It would only work once for everytime I open or restart my computer, quite frustrating.

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.

**Comment by kasugasan** [comment]
Hi, will Polarr be automatically updated? I would like to wait for the update rather than getting a refund.

**Comment by bwang29** [comment]
The app should not have the issues anymore now.
