### ISSUE TITLE
How to associate Image-Files with polarr pro (Windows 10)?

### ISSUE THREAD

**Issue by sebwag** [Polarrco/polarr_windows_support#6]
I want to open jpgs with polarr via double click.

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.

**Comment by bwang29** [comment]
Also, associate apps with Polarr will be supported too.
