### ISSUE TITLE
Payment and Download

### ISSUE THREAD

**Issue by Kwist-Muc** [Polarrco/polarr_windows_support#8]
Hi.
I've bought it today and then I had a system crash. So ihave to reinstall the pro version, and the market gives me only a possibility to buy  it a second time is it correct this way? I mean 99 cent is ok. also twice, but what if i have to do it more often and buy it for the full price???

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.
