### ISSUE TITLE
Picture keeps returning from zoom when tools are used

### ISSUE THREAD

**Issue by nicfed** [Polarrco/polarr_windows_support#9]
If I zoom in on a picture - and make a radial mask - every time I try to use a tool or adjust the radial mask, the window (viewport) of the picture automatically zoom out to full picture. That makes it very difficult to adjust the settings with the tools.

**Comment by bwang29** [comment]
We've been developing a brand new version for Windows 7/8/10 in the past three months and it is expected to release this end of month, with brand new UI, new rendering engine that's a lot faster and resolve all issues related to graphic driver.

For the time being. You can ask for a refund by sending a receipt to support@polarr.co for a refund.

**Comment by nicfed** [comment]
No need for a refund - looking forward to the new version
